### PR TITLE
Persist local folder path on `localStorage`

### PR DESCRIPTION
**Pull request by murilopolese**
Once user has selected a local folder (file manager) it should remember next time opening the editor.

### CODE REVIEW

**Review by ubidefeo — COMMENTED** [review]
I have been able to make it work once built, but running with `npm run dev` did not make the selected folder persist

**Comment by murilopolese** [comment]
> I have been able to make it work once built, but running with `npm run dev` did not make the selected folder persist

Does it log any error or any cue on why it won't persist on dev environment? I am not being able to reproduce it.

**Review by ubidefeo — APPROVED** [review]
rework of the enable/disable save and `cancel` operations fix my issues

**Review by ubidefeo — APPROVED** [review]
rework of the enable/disable save and `cancel` operations fix my issues

**Pull request merged**
