### PR TITLE
Show filename transfer

### PR DESCRIPTION
**Pull request by murilopolese**
Show name of the file being transferred.

### CODE REVIEW

**Review by ubidefeo — COMMENTED** [review]
I still only see "Transferring file" and the percentage on the next line.
no file name

**Review by ubidefeo — APPROVED** [review]
Showing file names for folder uploads will come later, single file(s) uploads will show the file name

**Comment by murilopolese** [comment]
I will have a look on how to show the name of the files that are being uploaded inside the folders, shouldn't be hard.

**Comment by murilopolese** [comment]
Included the file names with relative path to the folder upload:

Screenshot from 2024-11-07 08-50-11

**Review by ubidefeo — APPROVED** [review]
transferred a folder with 3 levels of subfolders down.
worked as expected

**Pull request merged**
