### PR TITLE
Making sure save is disabled

### PR DESCRIPTION
**Pull request by murilopolese**
When selected device is disk and there is no folder selected, the save button shouldn't be clickable

### CODE REVIEW

**Comment by murilopolese** [comment]
https://github.com/arduino/lab-micropython-editor/issues/33

**Comment by ubidefeo** [comment]
this can still be triggered, although in a convoluted way

* open Editor
* do not select folder
* rename `undefined` to something
* Save button is still disabled
* click on the file name again
* Save button is enabled and can save


https://user-images.githubusercontent.com/1894487/217252432-996c501a-5e52-4415-88cc-1101fe2ed20b.mp4

**Comment by murilopolese** [comment]
> this can still be triggered, although in a convoluted way

Thanks for catching this one, I made a mistake on the logic but now it should be fixed. Can you break it, @ubidefeo ?? hehehe

**Review by ubidefeo — APPROVED** [review]
LGTM

**Pull request merged**
