### PR TITLE
Release Candidate v0.6

### PR DESCRIPTION
**Pull request by murilopolese**
Bugfixes:

- Every user when first launching the editor and connecting a board, is confused by the terminal taking so much space and don’t understand they can resize it
- When the board is connected, the word under the connect button should be disconnected
- When a person clicks on disconnect it should not see the serial board list unless you click
- Adjust file control button sizes
- Refers to "serial" as "board" on confirmation prompts

Features:

- UI app should be able to specify the electron app size constraint
- Person should be able to confirm or deny file replacement/ovewrite/delete

### CODE REVIEW

**Review by ubidefeo — APPROVED** [review]
it all looks good, thank you

**Comment by ubidefeo** [comment]
@murilopolese 
I see this error in the CI, related to lockFileVersion.
Can you take a look?

Thank you
u.




```
Run # See: https://www.electron.build/code-signing
[190](https://github.com/arduino/lab-micropython-editor/actions/runs/3742033817/jobs/6352432884#step:4:191)
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
[191](https://github.com/arduino/lab-micropython-editor/actions/runs/3742033817/jobs/6352432884#step:4:192)
npm ERR! cb() never called!
[192](https://github.com/arduino/lab-micropython-editor/actions/runs/3742033817/jobs/6352432884#step:4:193)

[193](https://github.com/arduino/lab-micropython-editor/actions/runs/3742033817/jobs/6352432884#step:4:194)
npm ERR! This is an error with npm itself. Please report this error at:
[194](https://github.com/arduino/lab-micropython-editor/actions/runs/3742033817/jobs/6352432884#step:4:195)
npm ERR!     <https://npm.community/>
[195](https://github.com/arduino/lab-micropython-editor/actions/runs/3742033817/jobs/6352432884#step:4:196)

[196](https://github.com/arduino/lab-micropython-editor/actions/runs/3742033817/jobs/6352432884#step:4:197)
npm ERR! A complete log of this run can be found in:
[197](https://github.com/arduino/lab-micropython-editor/actions/runs/3742033817/jobs/6352432884#step:4:198)
npm ERR!     /Users/runner/.npm/_logs/2022-12-20T15_59_16_107Z-debug.log
[198](https://github.com/arduino/lab-micropython-editor/actions/runs/3742033817/jobs/6352432884#step:4:199)
Error: Process completed with exit code 1.
```

**Comment by murilopolese** [comment]
@ubidefeo fixed!

**Comment by per1234** [comment]
@murilopolese the error is because the Node.js version used during the build was not actually updated by https://github.com/arduino/lab-micropython-editor/pull/26

This line must be changed:

https://github.com/arduino/lab-micropython-editor/blob/8da4a08748d6bfb7b023d8b86aef9cafa161de29/.github/workflows/build.yml#L38

Reference:

https://github.com/actions/setup-node#supported-version-syntax

**Pull request merged**
